#!/bin/bash -e
# vim: set ts=2 sw=2 :

fresh freshshell/fresh bin/fresh --bin

FRESH_LOCAL=~
FRESH_MINE=~/.fresh/source/vic/...

fresh_mine (){
  source $FRESH_MINE/fresh/$1
}

fresh_mine_get (){
  source $FRESH_MINE/install/$1.sh
}

fresh_vic (){
  fresh vic/... $@
}

case x$OSTYPE in
  xlinux*)
    fresh_mine linux
    ;;
  xdarwin*)
    fresh_mine darwin
    ;;
esac

fresh_mine common
fresh_mine ruby
