#!/bin/bash -e
# vim: set tw=2 :
FRESH_LOCAL=~
TREEDOT=~/.fresh/source/vic/...

fresh freshshell/fresh bin/fresh --bin
fresh vic/... config/slate

[ ! -d ~/.zprezto ] && source $TREEDOT/install/prezto.sh
if [ -d ~/.zprezto ]; then
  rm ~/.zshrc
  fresh .zprezto/runcoms/zshrc --file=~/.zshrc
  fresh vic/... zsh/prezto/zshrc --file=~/.zshrc
fi

[ ! -d ~/.spf13-vim-3 ] && source $TREEDOT/install/spf13-vim.sh
if [ -d ~/.spf13-vim-3 ]; then
  rm ~/.vimrc.local
  rm ~/.vimrc.bundles.local
  fresh vic/... vim/spf13/vimrc.local
  fresh vic/... vim/spf13/vimrc.bundles.local
fi

